export { default as WorkspaceLogo } from './WorkspaceLogo.svg'
export { default as EyeIcon } from './EyeIcon.svg'
export { default as EyeCloseIcon } from './EyeCloseIcon.svg'
export { default as WorkspaceLogo2 } from './WorkspaceLogo2.svg'
export { default as SearchIcon } from './SearchIcon.svg'
export { default as AlramIcon } from './AlramIcon.svg'
export { default as LogoutIcon } from './LogoutIcon.svg'
